/**
* system of equations >
* * let:
* x[i + 1] = x[i] + 2y[i] + z[i] + 3 + 2i
* y[i + 1] = 5x[i] + y[i]  + 5z[i] + i
* z[i + 1] = x[i] + 2y[i] + 3z[i] + (2i + 3)^2
* vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
*
* x[i+1] = x[i] + 2y[i] + z[i] + 0(i^2) + 2i + 3
* y[i+1] = 5x[i] + y[i]  + 5z[i] + 0(i^2) + 1i + 0
* z[i+1] = x[i] + 2y[i] + 3z[i] + 4(i^2) + 12i + 9
*
* * state :
* S_i     = { x[i],   y[i],   z[i],   i^2,     i,     1 }
* S_{i+1} = { x[i+1], y[i+1], z[i+1], (i+1)^2, (i+1), 1 }
* * Transition Matrix (T) mapping S_i to S_{i+1}:
* [ 1  2  1  0  2  3 ]   [ x[i] ]     [ x[i+1]  ]
* [ 5  1  5  0  1  0 ]   [ y[i] ]     [ y[i+1]  ]
* [ 1  2  3  4 12  9 ] * [ z[i] ]  =  [ z[i+1]  ]
* [ 0  0  0  1  2  1 ]   [ i^2  ]     [ (i+1)^2 ]
* [ 0  0  0  0  1  1 ]   [ i    ]     [ (i+1)   ]
* [ 0  0  0  0  0  1 ]   [ 1    ]     [ 1       ]
* *
* to handle polynomials:
* - (i+1)^2 is generated by taking: (1 * i^2) + (2 * i) + (1 * 1)
* - (i+1)   is generated by taking:               (1 * i) + (1 * 1)
* - 1       is maintained by taking:                        (1 * 1)
*
*
* (O(6*6*(log(n))) => (O(log(n))
*/

void sys() {
  ll n;
  cin >> n;

  // base state (i = 0)
  matrix S = {{0},  // x_0
{0},  // y_0
{0},  // z_0
{0},  // 0^2
{0},  // 0
{1}}; // 1 const

  // transition T:
  matrix T = {
    {1, 2, 1, 0, 2, 3},   // x[i+1]
{5, 1, 5, 0, 1, 0},   // y[i+1]
{1, 2, 3, 4, 12, 9},  // z[i+1] = x + 2y + 3z + (4i^2 + 12i + 9)
{0, 0, 0, 1, 2, 1},   // (i+1)^2
{0, 0, 0, 0, 1, 1},   // (i+1)
{0, 0, 0, 0, 0, 1}    // 1
  };

  T = fas_pow(T, n);
  S = mul(T, S);

  cout << "x_n: " << S[0][0] << '\n';
  cout << "y_n: " << S[1][0] << '\n';
  cout << "z_n: " << S[2][0] << '\n';
}